version: '3.8'

services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/shandianguozi/official-website:latest
    container_name: official-website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
